name: Check version

on:
  workflow_call:
    outputs:
      version:
        description: 'Package version'
        value: ${{ steps.check_version.outputs.version }}
      is_changed:
        description: 'Package version state'
        value: ${{ steps.check_version.outputs.is_changed }}

jobs:
  check-version:
    runs-on: ubuntu-latest

    outputs:
      is_changed: ${{ steps.check_version.outputs.is_changed }}
      version: ${{ steps.check_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check version
        id: get_current_version
        run: |
          CURR_VERSION=$(grep '"version":' package.json | sed -E 's/.*"([^"]+)".*/\1/')
          echo "Current version in package.json: $CURR_VERSION"
          echo "version=$CURR_VERSION" >> $GITHUB_OUTPUT

      - name: Get previous version from package.json
        id: get_previous_version
        run: |
          PREV_VERSION=$(git show HEAD~1:package.json | grep '"version":' | sed -E 's/.*"([^"]+)".*/\1/' || echo "none")
          echo "Previous version in package.json: $PREV_VERSION"
          echo "prev_version=$PREV_VERSION" >> $GITHUB_OUTPUT

      - name: Check version increment
        id: check_version
        run: |
          echo "Previous version: ${{ steps.get_previous_version.outputs.prev_version }}"
          echo "Current version: ${{ steps.get_current_version.outputs.version }}"
          if [ "$PREV_VERSION" = "none" ] || [ "${{ steps.get_current_version.outputs.version }}" != "${{ steps.get_previous_version.outputs.prev_version }}" ]; then
            echo "is_changed=true" >> $GITHUB_OUTPUT
          else
            echo "is_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Output package version state
        run: |
          echo "Version changed: ${{ steps.check_version.outputs.is_changed }}"