name: Deploy

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version"
        required: true
        type: string
      package-version:
        description: "Package version"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-${{inputs.package-version}}
          path: dist

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: ${{ inputs.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Configure NPM to use registry with authentication
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
