name: Workflow

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  check-version:
    uses: Sovgut/state/.github/workflows/check-version.yml@main

  build:
    needs:
      - check-version
    if: needs.check-version.outputs.is_changed == 'true'
    uses: Sovgut/state/.github/workflows/build.yml@main
    with:
      node_version: '20.x'
      package_version: ${{ needs.check-version.outputs.version }}

  test:
    needs:
      - check-version
      - build
    uses: Sovgut/state/.github/workflows/test.yml@main
    with:
      node_version: '20.x'

  deploy:
    needs:
      - check-version
      - build
      - test
    uses: Sovgut/state/.github/workflows/deploy.yml@main
    with:
      package_version: ${{ needs.check-version.outputs.version }}