name: Workflow

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  check-version:
    name: Version Check
    uses: Sovgut/state/.github/workflows/check-version.yml@main

  build:
    name: Build
    needs:
      - check-version
    if: needs.check-version.outputs.is-changed == 'true'
    uses: Sovgut/state/.github/workflows/build.yml@main
    with:
      node-version: '20.x'
      package-version: ${{ needs.check-version.outputs.version }}

  test:
    name: Test
    needs:
      - check-version
    if: needs.check-version.outputs.is-changed == 'true'
    uses: Sovgut/state/.github/workflows/test.yml@main
    with:
      node-version: '20.x'

  deploy-npm:
    name: Deploy
    needs:
      - check-version
      - build
      - test
    uses: Sovgut/state/.github/workflows/deploy-npm.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      node-version: '20.x'
      package-version: ${{ needs.check-version.outputs.version }}

  deploy-github:
    name: Deploy
    needs:
      - check-version
      - build
      - test
    uses: Sovgut/state/.github/workflows/deploy-github.yml@main
    with:
      node-version: '20.x'
      package-version: ${{ needs.check-version.outputs.version }}
